---
# Ansible playbook to install HAProxy

- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for Python to become available
      raw: while [ ! -e /usr/bin/python ]; do echo 'waiting for python (5s)'; sleep 5; done; echo 'python available'
      changed_when: false

- hosts: all
  gather_facts: yes
  become: True
  tasks:
    - import_role:
        role: ubuntu
      tags: role-ubuntu

- hosts: haproxy
  become: True
  tasks:
    - import_role:
        role: haproxy
      vars:
        haproxy_frontend_port: 80
        haproxy_backend_port: 80
        haproxy_backend_group: backend_node
        haproxy_global_stats_enable: true
      tags: role-haproxy
