- name: Install Ansible prerequisites
  hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: Install python2
      raw: sudo apt-get -y install python-simplejson

- hosts: all
  tasks:
    - import_role:
        role: ubuntu
      tags: role-ubuntu

    - import_role:
        role: ansible
      tags: role-ansible

    - import_role:
        role: terraform
      tags: role-terraform

    - import_role:
        role: packer
      tags: role-packer
