---
# Ansible playbook to call the roles required to deploy our Ethereum stack

- hosts: eth_node
  become: True
  become_user: root
  vars:
    data_vol: /dev/sda
    data_dir: /opt/geth/.ethereum
  tasks:
    - import_role:
        role: ubuntu
      tags: role-ubuntu

    - name: Format data volume
      filesystem:
        dev: '{{data_vol}}'
        fstype: ext4

    - name: Mount data volume
      mount:
        path: '{{data_dir}}'
        src: '{{data_vol}}'
        fstype: ext4
        state: mounted
