#cloud-config
users:
  - name: ansible
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${public_key}

packages:
  - python
  - python-pip
  - python-requests
  - curl
  - nginx

runcmd:
  - echo "Welcome to $(curl http://169.254.169.254/metadata/v1/hostname)!" > /var/www/html/index.nginx-debian.html
