---
# Ansible playbook to install Parity Ethereum full node with data volume

- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for Python to become available
      raw: while [ ! -e /usr/bin/python ]; do echo 'waiting for python (5s)'; sleep 5; done; echo 'python available'

- hosts: parity_full
  become: True
  become_user: root
  vars:
    data_vol: /dev/sda
    data_dir: /opt/parity

  tasks:

    - name: Mount data volume
      mount:
        path: '{{data_dir}}'
        src: '{{data_vol}}'
        fstype: ext4
        state: mounted
      tags: datavol

    - import_role:
        role: ubuntu
      tags: role-ubuntu
  
    - import_role:
        role: parity
      vars:
        parity_sync_mode: active
        parity_chain: kovan
        parity_datadir: /data
      tags: role-parity
