---
# Ansible playbook to install Parity Ethereum light client

- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for Python to become available
      raw: while [ ! -e /usr/bin/python ]; do echo 'waiting for python (5s)'; sleep 5; done; echo 'python available'
      changed_when: false


- hosts: parity_light
  become: True
  become_user: root
  tasks:
    - import_role:
        role: ubuntu
      tags: role-ubuntu

    - import_role:
        role: parity
      vars:
        parity_sync_mode: light
        parity_cache: 3072
        parity_chain: kovan
      tags: role-parity
